services:
  smartdns:
    image: pymumu/smartdns:latest
    container_name: smartdns
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 6080:6080
    volumes:
      - "./config:/etc/smartdns"
      - "./data:/var/lib/smartdns"
    network_mode: "bridge"